# Generated by Django 6.0.4 on 2026-04-18 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_type', models.CharField(choices=[('LABOUR', 'Praca'), ('INFRASTRUCTURE', 'Infrastruktura'), ('LICENSES', 'Licencje'), ('OTHER', 'Inne')], max_length=20)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='projects.project')),
            ],
            options={
                'verbose_name': 'Kategoria budżetu',
                'verbose_name_plural': 'Kategorie budżetu',
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wpis czasu pracy',
                'verbose_name_plural': 'Wpisy czasu pracy',
                'ordering': ['-date'],
            },
        ),
    ]
