# Generated by Django 6.0.4 on 2026-04-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_timesheet_rejected_at_timesheet_rejected_by_and_more'),
        ('projects', '0002_alter_project_options_alter_project_budget_planned_and_more'),
        ('tasks', '0003_alter_task_options_alter_taskreview_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetcategory',
            options={'ordering': ['project', 'name'], 'verbose_name': 'kategorię budżetu', 'verbose_name_plural': 'kategorie budżetu'},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-date'], 'verbose_name': 'wpis czasu pracy', 'verbose_name_plural': 'wpisy czasu pracy'},
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='category_type',
            field=models.CharField(choices=[('LABOUR', 'Praca'), ('INFRASTRUCTURE', 'Infrastruktura'), ('LICENSES', 'Licencje'), ('OTHER', 'Inne')], max_length=20, verbose_name='Typ kategorii'),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kwota planowana'),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kwota wydana'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zatwierdzenia'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdzone przez'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Godziny'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Zatwierdzone'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data odrzucenia'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Odrzucone przez'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Powód odrzucenia'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='tasks.task', verbose_name='Zadanie'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
