# Generated by Django 6.0.4 on 2026-04-18 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('INITIATION', 'Inicjacja'), ('PLANNING', 'Planowanie'), ('EXECUTION', 'Realizacja'), ('MONITORING', 'Monitorowanie'), ('CLOSED', 'Zamknięty')], default='INITIATION', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Niski'), ('MEDIUM', 'Średni'), ('HIGH', 'Wysoki'), ('CRITICAL', 'Krytyczny')], default='MEDIUM', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_planned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'ordering': ['-created_at'],
            },
        ),
    ]
