# Generated by Django 6.0.4 on 2026-04-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'projekt', 'verbose_name_plural': 'projekty'},
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_planned',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budżet planowany'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Budżet wydany'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='Nazwa klienta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Niski'), ('MEDIUM', 'Średni'), ('HIGH', 'Wysoki'), ('CRITICAL', 'Krytyczny')], default='MEDIUM', max_length=10, verbose_name='Priorytet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Kierownik projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('INITIATION', 'Inicjacja'), ('PLANNING', 'Planowanie'), ('EXECUTION', 'Realizacja'), ('MONITORING', 'Monitorowanie'), ('CLOSED', 'Zamknięty')], default='INITIATION', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
    ]
