# Generated by Django 6.0.4 on 2026-04-18 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('probability', models.IntegerField(choices=[(1, 'Bardzo niskie'), (2, 'Niskie'), (3, 'Średnie'), (4, 'Wysokie'), (5, 'Bardzo wysokie')])),
                ('impact', models.IntegerField(choices=[(1, 'Bardzo niski'), (2, 'Niski'), (3, 'Średni'), (4, 'Wysoki'), (5, 'Bardzo wysoki')])),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Zidentyfikowane'), ('ANALYSED', 'Analizowane'), ('MITIGATED', 'Mitygowane'), ('CLOSED', 'Zamknięte')], default='IDENTIFIED', max_length=15)),
                ('mitigation_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Ryzyko',
                'verbose_name_plural': 'Ryzyka',
                'ordering': ['-created_at'],
            },
        ),
    ]
