# Generated by Django 6.0.4 on 2026-04-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_project_budget_planned_and_more'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risk',
            options={'ordering': ['-created_at'], 'verbose_name': 'ryzyko', 'verbose_name_plural': 'ryzyka'},
        ),
        migrations.AlterField(
            model_name='risk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.IntegerField(choices=[(1, 'Bardzo niski'), (2, 'Niski'), (3, 'Średni'), (4, 'Wysoki'), (5, 'Bardzo wysoki')], verbose_name='Wpływ'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='mitigation_plan',
            field=models.TextField(blank=True, null=True, verbose_name='Plan mitygacji'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability',
            field=models.IntegerField(choices=[(1, 'Bardzo niskie'), (2, 'Niskie'), (3, 'Średnie'), (4, 'Wysokie'), (5, 'Bardzo wysokie')], verbose_name='Prawdopodobieństwo'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('IDENTIFIED', 'Zidentyfikowane'), ('ANALYSED', 'Analizowane'), ('MITIGATED', 'Mitygowane'), ('CLOSED', 'Zamknięte')], default='IDENTIFIED', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
    ]
