# Generated by Django 6.0.4 on 2026-04-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'użytkownika', 'verbose_name_plural': 'użytkownicy'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active_employee',
            field=models.BooleanField(default=True, verbose_name='Aktywny pracownik'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('PM', 'Project Manager'), ('ANALYST', 'Analityk biznesowy'), ('DEVELOPER', 'Developer'), ('TESTER', 'Tester/QA')], default='DEVELOPER', max_length=20, verbose_name='Rola'),
        ),
    ]
