# Generated by Django 6.0.4 on 2026-04-18 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Szkic'), ('SUBMITTED', 'Złożony'), ('ANALYSED', 'Analizowany'), ('APPROVED', 'Zatwierdzony'), ('REJECTED', 'Odrzucony')], default='DRAFT', max_length=10)),
                ('impact_scope', models.TextField()),
                ('impact_time', models.IntegerField(help_text='Liczba dni')),
                ('impact_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_changes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wniosek o zmianę',
                'verbose_name_plural': 'Wnioski o zmianę',
                'ordering': ['-created_at'],
            },
        ),
    ]
