# Generated by Django 6.0.4 on 2026-04-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
        ('projects', '0002_alter_project_options_alter_project_budget_planned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'wniosek o zmianę', 'verbose_name_plural': 'wnioski o zmianę'},
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_changes', to=settings.AUTH_USER_MODEL, verbose_name='Decyzja wydana przez'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data decyzji'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='impact_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Wpływ na koszt'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='impact_scope',
            field=models.TextField(verbose_name='Zakres wpływu'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='impact_time',
            field=models.IntegerField(help_text='Liczba dni', verbose_name='Wpływ na czas (dni)'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_changes', to=settings.AUTH_USER_MODEL, verbose_name='Wnioskodawca'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Szkic'), ('SUBMITTED', 'Złożony'), ('ANALYSED', 'Analizowany'), ('APPROVED', 'Zatwierdzony'), ('REJECTED', 'Odrzucony')], default='DRAFT', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
    ]
