# Generated by Django 6.0.4 on 2026-04-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_project_budget_planned_and_more'),
        ('tasks', '0002_add_task_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'zadanie', 'verbose_name_plural': 'zadania'},
        ),
        migrations.AlterModelOptions(
            name='taskreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'przegląd zadania', 'verbose_name_plural': 'przeglądy zadań'},
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Rzeczywiste godziny'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Przypisany do'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(verbose_name='Termin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Szacowane godziny'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Niski'), ('MEDIUM', 'Średni'), ('HIGH', 'Wysoki'), ('CRITICAL', 'Krytyczny')], default='MEDIUM', max_length=10, verbose_name='Priorytet'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Do zrobienia'), ('IN_PROGRESS', 'W trakcie'), ('IN_REVIEW', 'W przeglądzie'), ('DONE', 'Zakończone'), ('BLOCKED', 'Zablokowane')], default='TODO', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data przeglądu'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='result',
            field=models.CharField(choices=[('APPROVED', 'Zatwierdzone'), ('REJECTED', 'Odrzucone')], max_length=10, verbose_name='Wynik'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Recenzent'),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tasks.task', verbose_name='Zadanie'),
        ),
    ]
