# Generated by Django 6.0.4 on 2026-04-18 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('req_type', models.CharField(choices=[('FUNCTIONAL', 'Funkcjonalne'), ('NON_FUNCTIONAL', 'Niefunkcjonalne')], max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Niski'), ('MEDIUM', 'Średni'), ('HIGH', 'Wysoki'), ('CRITICAL', 'Krytyczny')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Szkic'), ('APPROVED', 'Zatwierdzone'), ('IMPLEMENTED', 'Zaimplementowane'), ('VERIFIED', 'Zweryfikowane')], default='DRAFT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requirements', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project')),
            ],
            options={
                'verbose_name': 'Wymaganie',
                'verbose_name_plural': 'Wymagania',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WBSElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='requirements_wbs.wbselement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_elements', to='projects.project')),
            ],
            options={
                'verbose_name': 'Element WBS',
                'verbose_name_plural': 'Elementy WBS',
                'ordering': ['project', 'level', 'order'],
            },
        ),
    ]
