# Generated by Django 6.0.4 on 2026-04-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('requirements_wbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['code'], 'verbose_name': 'Wymaganie', 'verbose_name_plural': 'Wymagania'},
        ),
        migrations.AddField(
            model_name='requirement',
            name='code',
            field=models.CharField(default='REQ-000', max_length=20),
        ),
        migrations.AddField(
            model_name='requirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Wysoki'), ('MEDIUM', 'Średni'), ('LOW', 'Niski')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_type',
            field=models.CharField(choices=[('FUNCTIONAL', 'Funkcjonalne'), ('NON_FUNCTIONAL', 'Niefunkcjonalne')], default='FUNCTIONAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Szkic'), ('APPROVED', 'Zatwierdzone'), ('IMPLEMENTED', 'Zrealizowane'), ('REJECTED', 'Odrzucone')], default='DRAFT', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('project', 'code')},
        ),
    ]
