# Generated by Django 6.0.4 on 2026-04-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_wbs', '0002_add_code_updated_at_fix_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wbselement',
            options={'ordering': ['order'], 'verbose_name': 'Element WBS', 'verbose_name_plural': 'Elementy WBS'},
        ),
        migrations.RemoveField(
            model_name='wbselement',
            name='level',
        ),
        migrations.AddField(
            model_name='wbselement',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
