# Generated by Django 6.0.4 on 2026-04-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_project_budget_planned_and_more'),
        ('requirements_wbs', '0003_wbs_add_code_updated_at_remove_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['code'], 'verbose_name': 'wymaganie', 'verbose_name_plural': 'wymagania'},
        ),
        migrations.AlterModelOptions(
            name='wbselement',
            options={'ordering': ['order'], 'verbose_name': 'element WBS', 'verbose_name_plural': 'elementy WBS'},
        ),
        migrations.AlterField(
            model_name='requirement',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requirements', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Wysoki'), ('MEDIUM', 'Średni'), ('LOW', 'Niski')], default='MEDIUM', max_length=10, verbose_name='Priorytet'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_type',
            field=models.CharField(choices=[('FUNCTIONAL', 'Funkcjonalne'), ('NON_FUNCTIONAL', 'Niefunkcjonalne')], default='FUNCTIONAL', max_length=15, verbose_name='Typ wymagania'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Szkic'), ('APPROVED', 'Zatwierdzone'), ('IMPLEMENTED', 'Zrealizowane'), ('REJECTED', 'Odrzucone')], default='DRAFT', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolejność'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='requirements_wbs.wbselement', verbose_name='Element nadrzędny'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_elements', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
    ]
