# Generated by Django 6.0.4 on 2026-04-18 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(choices=[('PM', 'Project Manager'), ('ANALYST', 'Analityk'), ('DEVELOPER', 'Programista'), ('TESTER', 'Tester')], max_length=15)),
                ('availability_percent', models.IntegerField(default=100)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Członek zespołu',
                'verbose_name_plural': 'Członkowie zespołu',
                'ordering': ['project', 'user'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
