# Generated by Django 6.0.4 on 2026-04-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_project_budget_planned_and_more'),
        ('resources', '0002_add_hourly_rate_to_projectmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ['project', 'user'], 'verbose_name': 'członka zespołu', 'verbose_name_plural': 'członkowie zespołu'},
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='availability_percent',
            field=models.IntegerField(default=100, verbose_name='Dostępność (%)'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stawka godzinowa'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='joined_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data dołączenia'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role_in_project',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('ANALYST', 'Analityk'), ('DEVELOPER', 'Programista'), ('TESTER', 'Tester')], max_length=15, verbose_name='Rola w projekcie'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
